### ISSUE TITLE
Avoid premature insertion of lazy browsers

### ISSUE THREAD

**Issue by Loirooriol** [Loirooriol/Z-Notifier#15]
Consider using `TabBrowserInserted` (or `TabBrowserCreated`, [bug 1315222](https://bugzilla.mozilla.org/show_bug.cgi?id=1315222)) instead of `TabOpen`.
Probably this will greatly reduce compatibility with old Firefox versions, though.

**Comment by richardnpaul** [comment]
It depends on what the users are using.  FF52 seems not to bad to me, however, any Palemoon users wouldn't be able to use this version of the extension (there's always x-notifier reloaded but that's not being updated as regularly as this extension.)  

The option for Palemoon users to jump to Basilisk browser but if they're using Palemoon regularly is probably more due to the Australis interface changes being abhorent to them.  I'm not a plugin developer but are you able to feature check this and provide a fallback for compatibility?

**Comment by Loirooriol** [comment]
@richardnpaul For HTML events I could use `'ontabbrowserinserted' in gBrowser.tabContainer` but this is a custom event.

Another approach could be using `TabOpen` but then check is the browser is lazy. `tab.linkedPanel` seemed the right check but then the add-on didn't work well.

And another alternative is modifying Firefox so that `addProgressListener` does not prematurely insert lazy browsers, https://bugzilla.mozilla.org/show_bug.cgi?id=1418009#c10
